name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make setup-tesseract
          make setup

      - name: Format
        run: |
          make format

      - name: Lint
        run: |
          make lint

      - name: Type check
        run: |
          make typecheck

      - name: Run tests
        run: |
          make test
